# -*- coding: utf-8 -*-
"""
K230 steel-ball detection with UART output.

UART frame format is generated by Yahboom's YbProtocol:
    $length,14,x,y,w,h,class_name#

Coordinates sent to the STM32 are based on the 1280x720 AI input frame:
    image center = (640, 360)
"""

import gc
import os
import time

from libs.PlatTasks import DetectionApp
from libs.PipeLine import PipeLine, ScopedTiming
from libs.Utils import *
from libs.YbProtocol import YbProtocol
from ybUtils.YbUart import YbUart


# The standard Yahboom board has no HDMI display. "lcd" still sends frames
# back to the CanMV IDE because the firmware enables IDE frame output.
display_mode = "lcd"
rgb888p_size = [1280, 720]

root_path = "/sdcard/mp_deployment_source/"

# These objects are initialized later so that partially created resources can
# still be released if startup fails.
uart = None
pipeline = None
detector = None

protocol = YbProtocol()


deploy_conf = read_json(root_path + "deploy_config.json")
kmodel_path = root_path + deploy_conf["kmodel_path"]
labels = deploy_conf["categories"]
confidence_threshold = deploy_conf["confidence_threshold"]
nms_threshold = deploy_conf["nms_threshold"]
model_input_size = deploy_conf["img_size"]
nms_option = deploy_conf["nms_option"]
model_type = deploy_conf["model_type"]

anchors = []
if model_type == "AnchorBaseDet":
    anchors = (
        deploy_conf["anchors"][0]
        + deploy_conf["anchors"][1]
        + deploy_conf["anchors"][2]
    )


def clear_previous_result(det_app):
    """Avoid re-sending a stale box when the current frame has no detection."""
    det_app.cur_result["boxes"] = []
    det_app.cur_result["scores"] = []
    det_app.cur_result["idx"] = []


def send_best_detection(result):
    """
    Send only one target per frame.

    If several steel balls are detected, select the box with the highest
    confidence score so that the gimbal does not receive several conflicting
    targets in the same frame.
    """
    boxes = result["boxes"]
    scores = result["scores"]
    class_ids = result["idx"]

    if len(boxes) == 0:
        return False

    best_index = 0
    best_score = float(scores[0])
    for i in range(1, len(scores)):
        score = float(scores[i])
        if score > best_score:
            best_score = score
            best_index = i

    box = boxes[best_index]
    x1 = int(box[0])
    y1 = int(box[1])
    x2 = int(box[2])
    y2 = int(box[3])
    width = x2 - x1
    height = y2 - y1

    class_id = int(class_ids[best_index])
    class_name = labels[class_id]

    packet = protocol.get_object_detect_data(
        x1, y1, width, height, class_name
    )
    uart.send(packet)

    center_x = x1 + width // 2
    center_y = y1 + height // 2
    return center_x, center_y, best_score


inference_mode = "video"
debug_mode = 0

frame_count = 0

# Enable cooperative exit handling before creating camera/display resources.
# CanMV IDE's Stop button is handled when os.exitpoint() is reached.
os.exitpoint(os.EXITPOINT_ENABLE)

try:
    # K230 communication port: IO9=TX, IO10=RX, 115200 8N1.
    uart = YbUart(baudrate=115200)

    pipeline = PipeLine(
        rgb888p_size=rgb888p_size,
        display_mode=display_mode,
    )
    pipeline.create()
    display_size = pipeline.get_display_size()

    detector = DetectionApp(
        inference_mode,
        kmodel_path,
        labels,
        model_input_size,
        anchors,
        model_type,
        confidence_threshold,
        nms_threshold,
        rgb888p_size,
        display_size,
        debug_mode=debug_mode,
    )
    detector.config_preprocess()

    while True:
        # Give CanMV IDE a reliable point at which to interrupt this loop.
        os.exitpoint()

        with ScopedTiming("total", 0):
            image_data = pipeline.get_frame()

            # DetectionApp in the supplied firmware retains cur_result when a
            # frame has no target, so clear it before each new inference.
            clear_previous_result(detector)
            result = detector.run(image_data)

            detector.draw_result(pipeline.osd_img, result)
            target = send_best_detection(result)
            pipeline.show_image()

            frame_count += 1
            if target and frame_count % 20 == 0:
                center_x, center_y, score = target
                print(
                    "Steel_ball center:",
                    center_x,
                    center_y,
                    "error:",
                    center_x - 640,
                    center_y - 360,
                    "score:",
                    round(score, 2),
                )

            gc.collect()

        # Yield briefly so IDE/USB control messages are serviced promptly.
        time.sleep_ms(1)

except KeyboardInterrupt:
    print("User stopped steel-ball detection.")

except BaseException as error:
    print("Steel-ball detection exception:", error)

finally:
    print("Releasing steel-ball detection resources...")

    # Release every resource even if one deinitialization call fails.
    if detector is not None:
        try:
            detector.deinit()
        except BaseException as error:
            print("Detector deinit warning:", error)

    if pipeline is not None:
        try:
            pipeline.destroy()
        except BaseException as error:
            print("Pipeline destroy warning:", error)

    if uart is not None:
        try:
            uart.deinit()
        except BaseException as error:
            print("UART deinit warning:", error)

    os.exitpoint(os.EXITPOINT_ENABLE_SLEEP)
    time.sleep_ms(100)
    gc.collect()
    print("Resources released.")
